sudo: required

services:
    - docker

before_install:
    - docker build -t vamsidhar444/loginapp .

script:
    - docker run vamsidhar444/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push vamsidhar444/loginapp

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: app-login
    env: AppLogin-env
    bucket_name: elasticbeanstalk-ap-south-1-679022722124
    bucket_path: login-app
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
